### ISSUE TITLE
Weapon inventory always returns null

### ISSUE THREAD

**Issue by IntelliCe** [koczadly/csgo-gsi#5]
I have called `setAllDataComponents()` for the `GSIConfig`, and I have checked the config file is generated correctly, while method `getWeaponsInventory()` always returns null. But the fact is that the GSI actually returns all weapons to the server.

I have collected the `RawJsonObject` of the context and the `state` in the `GSIObserver` recall, shown as below.

state(weapons not included):
```
"allplayers":{"76561198413350680":{"name":"Frankfort","clan":"HSMachine","observer_slot":2,"team":"ct","match_stats":{"kills":1,"assists":0,"deaths":1,"mvps":0,"score":2},"state":{"health":100,"armor":0,"helmet":false,"flashed":0,"smoked":0,"burning":0,"money":1250,"round_kills":0,"round_killhs":0,"round_totaldmg":0,"equip_value":400},"weapons":{},"position":{"x":-2197.34,"y":276.93,"z":-159.98},"forward":{"x":0.95,"y":0.3,"z":-0.1}} ......
```
RawJsonObject(weapons included):
```
"allplayers":{"76561198413350680":{"clan":"HSMachine","name":"Frankfort","observer_slot":2,"team":"CT","match_stats":{"kills":1,"assists":0,"deaths":1,"mvps":0,"score":2},"position":"-2197.34, 276.93, -159.98","forward":"0.95, 0.30, -0.10","state":{"health":100,"armor":0,"helmet":false,"flashed":0,"burning":0,"money":1250,"round_kills":0,"round_killhs":0,"round_totaldmg":0,"equip_value":400},"weapons":{"weapon_0":{"name":"weapon_knife_ursus","paintkit":"am_zebra","type":"Knife","state":"active"},"weapon_1":{"name":"weapon_usp_silencer","paintkit":"cu_usp_cut","type":"Pistol","ammo_clip":12,"ammo_clip_max":12,"ammo_reserve":24,"state":"holstered"},"weapon_2":{"name":"weapon_taser","paintkit":"default","ammo_clip":1,"ammo_clip_max":1,"ammo_reserve":0,"state":"holstered"}}} ......
```

Maybe the JSON parser has something wrong? Please check it. Thank you : )

**Comment by koczadly** [comment]
Will look into this asap and get back to you. Thanks for bringing it to my attention.

**Comment by koczadly** [comment]
I can certainly see there's a problem in the example you've shown, but when I manually feed your JSON string to the deserializer it seems to parse it correctly without returning null. I've just tried testing this out and it seems to work correctly for both the player and allplayers states.

Are you using the latest version of the library? How are you checking for null values?

Thanks

**Comment by koczadly** [comment]
Ah okay, thank you for the code and console log, thats made it a bit clearer.

What's happening here is you're trying to re-serialize the Java objects back into a JSON object (using `new Gson().toJson(...)`) — the problem here is that the library is only designed to work one way (as of now, at least), deserializing incoming JSON data. In your case, it's just serializing the inventory back into an empty object.

This should mean that, despite what's shown in your console logs, the actual value of the weapons should not be null (through `getWeaponsInventory()`. If you want to turn the whole thing into a JSON string or object, just use the one provided by the context instead of reserializing the existing objects.

Can you confirm that the weapon values are still null? eg. get a `PlayerState` from the `getPlayersStates()` map, and then call `getWeaponsInventory()` on that and check if its null.

**Comment by IntelliCe** [comment]
Issue solved. I got the weapons inventory from `player` instead of `allplayers`. `allplayers` contains weapon info, and `player` doesn't. Sorry for my careless and thanks for your enthusiastic help.😊

**Comment by koczadly** [comment]
No worries at all mate that's no problem. If you have any other issues or questions just let me know.
